services:
  puppeteer:
    image: ghcr.io/puppeteer/puppeteer:latest
    container_name: puppeteer
    command: node scrape.cjs
    init: true
    restart: unless-stopped
    volumes:
      - "./:/app"
    working_dir: /app
    expose:
      - "8000"
    security_opt:
      - seccomp=unconfined
    networks:
      - caddy_net
  transfersh:
    image: dutchcoders/transfer.sh:latest
    container_name: transfersh
    init: true
    restart: unless-stopped
    volumes:
      - ./transfersh/uploads:/var/uploads
      - ./transfersh/temp:/tmp
    user: "1000:1000"
    expose:
      - "8080"
    environment:
      - PROVIDER=local
      - BASEDIR=/var/uploads
      - TEMP_PATH=/tmp
      - MAX_UPLOAD_SIZE=500000
      - PURGE_DAYS=14
    networks:
      - caddy_net
  caddy:
    image: caddy:latest
    container_name: caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - caddy_net
networks:
  caddy_net:
    driver: bridge
volumes:
  caddy_data:
  caddy_config:
